# Generated by Django 3.0.6 on 2020-07-21 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdportfolioapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=250)),
                ('from_date', models.DateField()),
                ('to_date', models.DateField()),
                ('designation', models.CharField(max_length=250)),
                ('description', models.TextField()),
            ],
        ),
    ]
