# Generated by Django 3.0.6 on 2020-07-21 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdportfolioapp', '0002_experience'),
    ]

    operations = [
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('institution_name', models.CharField(max_length=250)),
                ('from_date', models.DateField()),
                ('to_date', models.DateField()),
                ('name_of_degree', models.CharField(max_length=250)),
            ],
        ),
    ]
